# -*- coding:utf-8 -*-
import os

env = os.getenv

ENVIRONMENT = env("ENVIRONMENT", "dev")
DEBUG = False

# MySQL配置
SQLALCHEMY_DATABASE_URI = env("SQLALCHEMY_DATABASE_URI", "sqlite://")
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_RECYCLE = int(env("SQLALCHEMY_POOL_RECYCLE", 7200))
SQLALCHEMY_POOL_SIZE = int(env("SQLALCHEMY_POOL_SIZE", 100))
SQLALCHEMY_POOL_TIMEOUT = int(env("SQLALCHEMY_POOL_TIMEOUT", 180))
